{% set name = "hyp3_metadata" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b61d1fe791afb01ded1ff39ef9c9d1f6dea101522588a68592cf8e4266390354

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=42
    - setuptools_scm >=3.4
    - wheel
  run:
    - python >={{ python_min }}
    - importlib-metadata
    - jinja2
    - gdal
    - pillow
    - python-dateutil

test:
  requires:
    - python {{ python_min }}
  imports:
    - hyp3_metadata
  commands:
    - python -m hyp3_metadata --help

about:
  home: https://github.com/ASFHyP3/hyp3-metadata-templates
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Package for generating HyP3 products' metadata

extra:
  recipe-maintainers:
    - jhkennedy
    - asjohnston-asf
    - jlrine2
